import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';

import '@/styles/globals.css';

const manrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr" className={manrope.className}>
      <body className="flex min-h-full flex-col">
        <div>Header</div>
        <main>{children}</main>
        <div>Footer</div>
      </body>
    </html>
  );
}
